name: Test and release when tagged

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ["test-py312"]
        numpy: ["numpy>=2.0.0,<2.1.0"]
        uncertainties: [null]
        extras: ["matplotlib==3.5.3", "babel==2.15 matplotlib==3.9.0"]
        mplflag: ["", "--mpl"]
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          environments: ${{ matrix.environment }}
          activate-environment: true

      - name: Install pip
        run: pixi add pip

      - name: Install numpy
        if: ${{ matrix.numpy != null }}
        run: pixi run -e ${{ matrix.environment }} pip install "${{matrix.numpy}}"

      - name: Install uncertainties
        if: ${{ matrix.uncertainties != null }}
        run: pixi run -e ${{ matrix.environment }} pip install "${{matrix.uncertainties}}"

      - name: Install extras
        if: ${{ matrix.extras != null }}
        run: pixi run -e ${{ matrix.environment }} pip install ${{matrix.extras}}

      - name: Install locales
        if: ${{ matrix.extras != null }}
        run: |
          sudo apt-get update
          sudo apt-get install language-pack-es language-pack-fr language-pack-ro
          sudo localedef -i es_ES -f UTF-8 es_ES
          sudo localedef -i fr_FR -f UTF-8 fr_FR
          sudo localedef -i ro_RO -f UTF-8 ro_RO

      - name: Install dependencies
        run: |
          sudo apt install -y graphviz
          pixi run -e ${{ matrix.environment }} pip install packaging

      - name: Install pytest-mpl
        if: contains(matrix.extras, 'matplotlib')
        run: pixi run -e ${{ matrix.environment }} pip install pytest-mpl
      - run: pixi run --environment ${{ matrix.environment }} test ${{ matrix.mplflag }} --mpl-results-path=mpl-results -rf pint/testsuite/test_matplotlib.py
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mpl-results-${{ strategy.job-index }}
          path: mpl-results
          if-no-files-found: ignore
